### PR TITLE
Modernize Google button

### PR DESCRIPTION
**Pull request by AbdulrhmnGhanem**
Google+ button is no longer the official button to login with google. So I just update it.

### CODE REVIEW

**Comment by MichalSzorad** [comment]
Thank you @AbdulrhmnGhanem, I'll make the release tomorrow!

**Comment by kykungz** [comment]
@MichalSzorad has this been published yet?

**Comment by robbm1** [comment]
I am also waiting for it @MichalSzorad.

**Comment by MichalSzorad** [comment]
@robbm1 I'll make sure it's deployed today. Apologies for any issues.

**Comment by robbm1** [comment]
No problem @MichalSzorad. Thanks for the update!

**Comment by MichalSzorad** [comment]
@robbm1 @kykungz @AbdulrhmnGhanem please use 3.1.2 to see the new google logo

**Pull request merged**
