### PR TITLE
Social media icon alignment issue resolved

### PR DESCRIPTION
**Pull request by ftechiesnitin**
Social Button Icon issue

### CODE REVIEW

**Comment by MichalSzorad** [comment]
Hello @ftechiesnitin,
thank you for contributing and caring! 

I will take a closer look at this PR later today.

Could you please format the document as it is not clear what has been changed. There are some spaces doing mess in the diff.

Thank you again!

**Comment by ftechiesnitin** [comment]
@MichalSzorad sure. I will change the spacing and retain to the old one.

**Comment by MichalSzorad** [comment]
@ftechiesnitin Sorry for the late response, react-social-login-buttons@2.0.0 will be released soon and this issue will be fixed.

**Comment by ftechiesnitin** [comment]
@MichalSzorad thanks for the update, but is it possible to know the timeline of react-social-login-buttons@2.0.0.

**Comment by MichalSzorad** [comment]
@ftechiesnitin I think May 14 will be a nice day to make a release.

**Pull request closed without merging**
