### PR TITLE
Add login with Buffer button and expose createSvgIcon

### PR DESCRIPTION
**Pull request by junaidatique**
Create Login with buffer icon plus exported createSvgIcon.js which was not exported. This will help users to use SVG icons.

### CODE REVIEW

**Comment by MichalSzorad** [comment]
Hi @junaidatique, thanks for the PR! 👍 

Could you please remove the package-lock.json file? We are using yarn for everything and I would not want to manage 2 lockfiles. 🙂 

Would you also mind adding a typescript definition for `createSvgIcon` to src/types.d.ts?
I think the snippet should be enough.
```tsx
declare const createSvgIcon: <T extends Function>(Component: T) => (props: { size: string | number }) => T
export {
  /// ...
  createSvgIcon,
}
```
The documentation in README.md should be also updated.

If not I can do it too.

After that I can merge the PR and hopefully make a release today.

**Comment by MichalSzorad** [comment]
I have another question.
I am also thinking that I would start following the [all-contributors specification](https://github.com/kentcdodds/all-contributors).

Would you be okay with me adding you as a contributor to the readme.md file? If yes, let me know. I would add your name, profile picture and a link to your github profile to the readme.md.

Great example of how it could look like can be found [here](https://www.npmjs.com/package/downshift) in the contributors section.

**Comment by junaidatique** [comment]
I have updated as recommended. Please recommend if I need to change anything.

**Comment by junaidatique** [comment]
Hi Thanks for considering me for the contributors section. My name is Junaid Atique. You can use my github profile image.

**Comment by MichalSzorad** [comment]
Thanks! I will release it today.

**Comment by junaidatique** [comment]
Thanks, What more value can I add to this repo?

**Pull request merged**
